# 数据源配置
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/myself?serverTimezone=UTC&characterEncoding=utf-8
        username: root
        password: 521qq521qq
